[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "KeepSSHFilesByPath"
MatchAction = "Snaffle"
Description = "Files with a path containing these strings are very very interesting."
MatchLocation = "FilePath"
WordListType = "Contains"
MatchLength = 0
WordList = [
    # this looks like the wrong number of backslashes?
    "\\\\\\.ssh\\\\", 
    ]
Triage = "Black"