[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayRubyByExtension"
MatchAction = "Relay"
RelayTargets = [
    "KeepRubyDbConnStrings",
    "KeepAwsKeysInCode",     # Generic Code Rule
    "KeepInlinePrivateKey",  # Generic Code Rule
    "KeepPassOrKeyInCode",   # Generic Code Rule
    "KeepSlackTokensInCode", # Generic Code Rule
    "KeepSqlAccountCreation" # Generic Code Rule
    ]
Description = "Files with these extensions will be searched for Rubby related strings."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.rb"]
Triage = "Green"