
[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayPsByExtension"
MatchAction = "Relay"
RelayTargets = [
    "KeepPsCredentials", 
    "KeepCmdCredentials",
    "KeepAwsKeysInCode",     # Generic Code Rule
    "KeepInlinePrivateKey",  # Generic Code Rule
    "KeepPassOrKeyInCode",   # Generic Code Rule
    "KeepSlackTokensInCode", # Generic Code Rule
    "KeepSqlAccountCreation" # Generic Code Rule
]
Description = "Files with these extensions will be searched for PowerShell related strings."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = [
        "\\.psd1", 
        "\\.psm1", 
        "\\.ps1"
]
Triage = "Green"