[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayRdpByExtension"
MatchAction = "Relay"
RelayTargets = ["KeepRdpPasswords"]
Description = "Look inside unattend.xml files for actual values."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.rdp"]
Triage = "Green"


