
[[ClassifierRules]]
EnumerationScope = "ContentsEnumeration"
RuleName = "KeepCSharpDbConnStrings"
MatchAction = "Snaffle"
Description = "Files with contents matching these regexen are very interesting."
MatchLocation = "FileContentAsString"
WordListType = "Regex"
MatchLength = 0
WordList = [
    "connectionstring.{1,200}passw"
]
Triage = "Red"