[[ClassifierRules]]
EnumerationScope = "FileEnumeration"
RuleName = "RelayCSharpByExtension"
MatchAction = "Relay"
RelayTargets = [
    "KeepCSharpDbConnStrings",
    "KeepCSharpViewstateKeys",
    "KeepAwsKeysInCode",     # Generic Code Rule
    "KeepInlinePrivateKey",  # Generic Code Rule
    "KeepPassOrKeyInCode",   # Generic Code Rule
    "KeepSlackTokensInCode", # Generic Code Rule
    "KeepSqlAccountCreation" # Generic Code Rule
]
Description = "Files with these extensions will be searched for CSharp and ASP.NET related strings."
MatchLocation = "FileExtension"
WordListType = "Exact"
MatchLength = 0
WordList = ["\\.aspx", 
"\\.ashx", 
"\\.asmx", 
"\\.asp", 
"\\.cshtml", 
"\\.cs", 
"\\.ascx",
"\\.config"
]
Triage = "Green"
